# Generated by Django 3.1.3 on 2020-11-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20201110_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Лайк', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.RemoveField(
            model_name='pictures',
            name='url',
        ),
        migrations.AddField(
            model_name='pictures',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo'),
            preserve_default=False,
        ),
    ]
