# Generated by Django 3.1.3 on 2020-11-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20201115_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rest_api.publication', verbose_name='Публиация'),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rest_api.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='like',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rest_api.publication', verbose_name='Публиация'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'publication', 'comment')},
        ),
    ]
