# Generated by Django 3.1.3 on 2020-11-16 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
