# Generated by Django 3.1.3 on 2020-12-05 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_remove_publication_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
