# Generated by Django 3.1.3 on 2020-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0016_auto_20201205_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(null=True, upload_to='photo'),
        ),
    ]
