# Generated by Django 3.1.3 on 2020-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0017_auto_20201205_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(default=None, upload_to='photo'),
            preserve_default=False,
        ),
    ]
