# Generated by Django 3.1.3 on 2020-12-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0020_auto_20201206_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='publication',
            field=models.ManyToManyField(blank=True, related_name='tags', to='rest_api.Publication', verbose_name='Публиация'),
        ),
    ]
