# Generated by Django 3.1.3 on 2020-12-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0021_auto_20201206_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default=None, max_length=128, unique=True, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
