# Generated by Django 3.1.3 on 2020-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0022_auto_20201206_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(default='', upload_to='photo/%Y/%m'),
        ),
    ]
