# Generated by Django 3.1.3 on 2020-12-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0023_auto_20201217_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
