# Generated by Django 3.1.3 on 2020-12-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0025_auto_20201226_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='photo/default.jpg', upload_to='photo'),
        ),
    ]
