# Generated by Django 3.1.3 on 2020-12-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0026_auto_20201226_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-date'], 'verbose_name': 'Публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
